#define N_NEIGHTBORS_TOROID 4
#define NEIGHTBOUR_NORTH_TOROID 0
#define NEIGHTBOUR_SOUTH_TOROID 1
#define NEIGHTBOUR_EAST_TOROID 2
#define NEIGHTBOUR_WEST_TOROID 3

#define MAX_DATA_BLOCK 4096

#define WRONG_ARGUMENT_ERROR_CODE -1
#define WRONG_NUMBER_OF_LAUNCHED_PROCESSES -2
#define NOT_ENOUGHT_DATA_FOR_PROCESSES -3
#define WRONG_FILE_PATH -4
#define STATUS_OK 0

#define ROOT 0
